### ISSUE TITLE
Drag and drop selection is not very responsive

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#142]
Testing microsoft/vscode#103174

I see a bunch of messages when I do a profile which is odd as I'd expect this to be all webview side unless a scroll happened:

![recording (10)](https://user-images.githubusercontent.com/2193314/88416107-75987100-cd94-11ea-9d94-ff0c1a597da4.gif)

**Comment by lramos15** [comment]
[hexeditor-1.2.0.zip](https://github.com/microsoft/vscode-hexeditor/files/4973337/hexeditor-1.2.0.zip)
Try this VSIX. I believe this was fixed by #92 which got merged in this morning.

**Comment by Tyriar** [comment]
This is still not fixed, the fps seems to drop to like 1-5 when dragging the selection around still.

**Comment by lramos15** [comment]
[drag-drop.zip](https://github.com/microsoft/vscode-hexeditor/files/4983447/drag-drop.zip)
Here's my performance profile. I don't feel any inherit sluggishness. The selection is all done on the webview side.

**Comment by Tyriar** [comment]
@lramos15 I was using a larger file, there may be some O(n)+ business going on, it was extremely sluggish for me

**Comment by lramos15** [comment]
@Tyriar I'm still unsure. I tested it on a 100mb file and it appears to drop a frame once in awhile, but isn't unusable for me. I think there is some performance tricks being done courtesy of @jeanp413 which sped things up more than before but causes a few more iterations of the selected elements. Due to the virtual render O(n)+ would be the n on the DOM not the n of the file.

**Comment by Tyriar** [comment]
[Profile-20200728T083600.zip](https://github.com/microsoft/vscode-hexeditor/files/4989390/Profile-20200728T083600.zip)


![image](https://user-images.githubusercontent.com/2193314/88687636-5c056b00-d0ad-11ea-9fd8-c3e6c8e5a4b4.png)

**Comment by Tyriar** [comment]
Looked into this a little, I found:

- The way selection is currently done by toggling classes on hundreds of elements is slow
- Layout shifts appear to be occurring but webview devtools doesn't want to show me where they are happening
- The elements query still seems to be slow after querying classes instead of the `data-offset` attribute

Given these issues, it will probably take a while to clean it up to get to 60fps.

**Comment by connor4312** [comment]
This is now smooth with the editor rework
